export const TRANSLATIONS = {
  en: {
    greeting: "Hello",
    farewell: "Goodbye",
    thankYou: "Thank you",
    please: "Please",
    yes: "Yes",
    no: "No",
    colors: {
      red: "Red",
      blue: "Blue",
      green: "Green",
      yellow: "Yellow",
      orange: "Orange",
      purple: "Purple",
      black: "Black",
      white: "White",
    },
    daysOfWeek: {
      monday: "Monday",
      tuesday: "Tuesday",
      wednesday: "Wednesday",
      thursday: "Thursday",
      friday: "Friday",
      saturday: "Saturday",
      sunday: "Sunday",
    },
    monthsOfYear: {
      january: "January",
      february: "February",
      march: "March",
      april: "April",
      may: "May",
      june: "June",
      july: "July",
      august: "August",
      september: "September",
      october: "October",
      november: "November",
      december: "December",
    },
    directions: {
      north: "North",
      south: "South",
      east: "East",
      west: "West",
    },
  },
  es: {
    greeting: "Hola",
    farewell: "Adiós",
    thankYou: "Gracias",
    please: "Por favor",
    yes: "Sí",
    no: "No",
    colors: {
      red: "Rojo",
      blue: "Azul",
      green: "Verde",
      yellow: "Amarillo",
      orange: "Naranja",
      purple: "Morado",
      black: "Negro",
      white: "Blanco",
    },
    daysOfWeek: {
      monday: "Lunes",
      tuesday: "Martes",
      wednesday: "Miércoles",
      thursday: "Jueves",
      friday: "Viernes",
      saturday: "Sábado",
      sunday: "Domingo",
    },
    monthsOfYear: {
      january: "Enero",
      february: "Febrero",
      march: "Marzo",
      april: "Abril",
      may: "Mayo",
      june: "Junio",
      july: "Julio",
      august: "Agosto",
      september: "Septiembre",
      october: "Octubre",
      november: "Noviembre",
      december: "Diciembre",
    },
    directions: {
      north: "Norte",
      south: "Sur",
      east: "Este",
      west: "Oeste",
    },
  },
  de: {
    greeting: "Hallo",
    farewell: "Auf Wiedersehen",
    thankYou: "Danke",
    please: "Bitte",
    yes: "Ja",
    no: "Nein",
    colors: {
      red: "Rot",
      blue: "Blau",
      green: "Grün",
      yellow: "Gelb",
      orange: "Orange",
      purple: "Lila",
      black: "Schwarz",
      white: "Weiß",
    },
    daysOfWeek: {
      monday: "Montag",
      tuesday: "Dienstag",
      wednesday: "Mittwoch",
      thursday: "Donnerstag",
      friday: "Freitag",
      saturday: "Samstag",
      sunday: "Sonntag",
    },
    monthsOfYear: {
      january: "Januar",
      february: "Februar",
      march: "März",
      april: "April",
      may: "Mai",
      june: "Juni",
      july: "Juli",
      august: "August",
      september: "September",
      october: "Oktober",
      november: "November",
      december: "Dezember",
    },
    directions: {
      north: "Norden",
      south: "Süden",
      east: "Osten",
      west: "Westen",
    },
  },
  jp: {
    greeting: "こんにちは",
    farewell: "さようなら",
    thankYou: "ありがとうございます",
    please: "お願いします",
    yes: "はい",
    no: "いいえ",
    colors: {
      red: "赤",
      blue: "青",
      green: "緑",
      yellow: "黄色",
      orange: "オレンジ",
      purple: "紫",
      black: "黒",
      white: "白",
    },
    daysOfWeek: {
      monday: "月曜日",
      tuesday: "火曜日",
      wednesday: "水曜日",
      thursday: "木曜日",
      friday: "金曜日",
      saturday: "土曜日",
      sunday: "日曜日",
    },
    monthsOfYear: {
      january: "1月",
      february: "2月",
      march: "3月",
      april: "4月",
      may: "5月",
      june: "6月",
      july: "7月",
      august: "8月",
      september: "9月",
      october: "10月",
      november: "11月",
      december: "12月",
    },
    directions: {
      north: "北",
      south: "南",
      east: "東",
      west: "西",
    },
  },
  pl: {
    greeting: "Cześć",
    farewell: "Do widzenia",
    thankYou: "Dziękuję",
    please: "Proszę",
    yes: "Tak",
    no: "Nie",
    colors: {
      red: "Czerwony",
      blue: "Niebieski",
      green: "Zielony",
      yellow: "Żółty",
      orange: "Pomarańczowy",
      purple: "Fioletowy",
      black: "Czarny",
      white: "Biały",
    },
    daysOfWeek: {
      monday: "Poniedziałek",
      tuesday: "Wtorek",
      wednesday: "Środa",
      thursday: "Czwartek",
      friday: "Piątek",
      saturday: "Sobota",
      sunday: "Niedziela",
    },
    monthsOfYear: {
      january: "Styczeń",
      february: "Luty",
      march: "Marzec",
      april: "Kwiecień",
      may: "Maj",
      june: "Czerwiec",
      july: "Lipiec",
      august: "Sierpień",
      september: "Wrzesień",
      october: "Październik",
      november: "Listopad",
      december: "Grudzień",
    },
    directions: {
      north: "Północ",
      south: "Południe",
      east: "Wschód",
      west: "Zachód",
    },
  },
  it: {
    greeting: "Ciao",
    farewell: "Arrivederci",
    thankYou: "Grazie",
    please: "Per favore",
    yes: "Sì",
    no: "No",
    colors: {
      red: "Rosso",
      blue: "Blu",
      green: "Verde",
      yellow: "Giallo",
      orange: "Arancione",
      purple: "Viola",
      black: "Nero",
      white: "Bianco",
    },
    daysOfWeek: {
      monday: "Lunedì",
      tuesday: "Martedì",
      wednesday: "Mercoledì",
      thursday: "Giovedì",
      friday: "Venerdì",
      saturday: "Sabato",
      sunday: "Domenica",
    },
    monthsOfYear: {
      january: "Gennaio",
      february: "Febbraio",
      march: "Marzo",
      april: "Aprile",
      may: "Maggio",
      june: "Giugno",
      july: "Luglio",
      august: "Agosto",
      september: "Settembre",
      october: "Ottobre",
      november: "Novembre",
      december: "Dicembre",
    },
    directions: {
      north: "Nord",
      south: "Sud",
      east: "Est",
      west: "Ovest",
    },
  },
};

export const LOCALES = [
  { locale: "en", fullName: "English", localName: "English" },
  { locale: "es", fullName: "Spanish", localName: "Español" },
  { locale: "de", fullName: "German", localName: "Deutsch" },
  { locale: "jp", fullName: "Japanese", localName: "日本語" },
  { locale: "it", fullName: "Italian", localName: "Italiano" },
  { locale: "pl", fullName: "Polish", localName: "Polski" },
];
